name: Prepare Release Asset

on:
  push:
    branches: 
      - master
      - experimental
  workflow_dispatch:

jobs:
  build:
    name: Prepare Release Asset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install native libs
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libcurl4-gnutls-dev libmosquitto-dev build-essential
    - name: Prepare LilyGoWatch-S3 configuration
      run: |
        mkdir -p ~/.platformio/boards
        cp LilyGoWatch-S3.json ~/.platformio/boards/
    - name: Run PlatformIO
      run: pio run --board LilyGoWatch-S3
